In [21]:
import pandas as pd

'''
create a example dataset
''' 
# four features and a class that is two categories
outlook = ['Sunny','Sunny','Overcast','Overcast','Rain','Rain']
temp = ['Hi','Hi','Hi','Lo','Lo','Lo']
humid = ['Hi','Hi','Lo','Lo','Hi','Hi']
wind = ['No','Yes','No','Yes','No','Yes']
decision = ['NP','NP','P','P','P','NP']

# show table about dataset
table = {'Outlook':outlook,'Temperature':temp,'Humidity':humid,'Windy':wind,'Decision':decision}
df = pd.DataFrame(data=table)
df

Outlook Temperature Humidity Windy Decision
0     Sunny          Hi       Hi    No       NP
1     Sunny          Hi       Hi   Yes       NP
2  Overcast          Hi       Lo    No        P
3  Overcast          Lo       Lo   Yes        P
4      Rain          Lo       Hi    No        P
5      Rain          Lo       Hi   Yes       NP

In [22]:
'''
preprocess the datasets
'''
from sklearn import preprocessing

# create labelEncoder
le = preprocessing.LabelEncoder()
# converting string labels into numbers
outlook_encoded= le.fit_transform(outlook)
temp_encoded= le.fit_transform(temp)
humid_encoded= le.fit_transform(humid)
wind_encoded= le.fit_transform(wind)
label_encoded= le.fit_transform(decision)
print('outlook:',outlook_encoded) # sunny:2 overcast:0 rain:1
print('temp:',temp_encoded) # high:0 low:1
print('humid:',humid_encoded) # high:0 low:1
print('wind:',wind_encoded) # no:0 yes:1
print('decision:',label_encoded) # no play:0 play:1

outlook: [2 2 0 0 1 1]
temp: [0 0 0 1 1 1]
humid: [0 0 1 1 0 0]
wind: [0 1 0 1 0 1]
decision: [0 0 1 1 1 0]


In [23]:
import numpy as np
# combine features into a single list of tuples
features = np.stack((outlook_encoded,temp_encoded,humid_encoded,wind_encoded),axis=1)
print('features:',features)

features: [[2 0 0 0]
 [2 0 0 1]
 [0 0 1 0]
 [0 1 1 1]
 [1 1 0 0]
 [1 1 0 1]]


In [28]:
'''
generating model
'''
from sklearn.naive_bayes import GaussianNB

# create a Gaussian Classifier
model = GaussianNB()

# train the model using the training sets
model.fit(features, label_encoded)

# predict output
predicted = model.predict([[2,0,1,0]]) # outlook=sunny, temp=high, humidity=low, windy=no
print('predicted value:',predicted)  # no play:0 play:1

predicted value: [1]
